"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class VesonImosPortActivitySlice(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PORT_ACTIVITIES_FIELD_NUMBER: builtins.int
    @property
    def port_activities(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___VesonImosPortActivity]: ...
    def __init__(self,
        *,
        port_activities: typing.Optional[typing.Iterable[global___VesonImosPortActivity]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["port_activities",b"port_activities"]) -> None: ...
global___VesonImosPortActivitySlice = VesonImosPortActivitySlice

class VesonImosPortActivity(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VOYAGE_NUM_FIELD_NUMBER: builtins.int
    PORT_CALL_NUM_FIELD_NUMBER: builtins.int
    ACTIVITY_TIME_FIELD_NUMBER: builtins.int
    ACTIVITY_NAME_FIELD_NUMBER: builtins.int
    ACTION_TYPE_FIELD_NUMBER: builtins.int
    PORT_FIELD_NUMBER: builtins.int
    COUNTRY_FIELD_NUMBER: builtins.int
    UNCTAD_CODE_FIELD_NUMBER: builtins.int
    VSL_NAME_FIELD_NUMBER: builtins.int
    IMO_NO_FIELD_NUMBER: builtins.int
    LOAD_OR_DISCHARGE_FIELD_NUMBER: builtins.int
    CARGO_GRADE_FIELD_NUMBER: builtins.int
    BL_QTY_FIELD_NUMBER: builtins.int
    CP_UNIT_FIELD_NUMBER: builtins.int
    COMMODITY_GROUP_FIELD_NUMBER: builtins.int
    voyage_num: builtins.int
    port_call_num: builtins.int
    @property
    def activity_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    activity_name: typing.Text
    action_type: typing.Text
    port: typing.Text
    country: typing.Text
    unctad_code: typing.Text
    vsl_name: typing.Text
    imo_no: builtins.int
    load_or_discharge: typing.Text
    cargo_grade: typing.Text
    bl_qty: builtins.float
    cp_unit: typing.Text
    commodity_group: typing.Text
    def __init__(self,
        *,
        voyage_num: builtins.int = ...,
        port_call_num: builtins.int = ...,
        activity_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        activity_name: typing.Text = ...,
        action_type: typing.Text = ...,
        port: typing.Text = ...,
        country: typing.Text = ...,
        unctad_code: typing.Text = ...,
        vsl_name: typing.Text = ...,
        imo_no: builtins.int = ...,
        load_or_discharge: typing.Text = ...,
        cargo_grade: typing.Text = ...,
        bl_qty: builtins.float = ...,
        cp_unit: typing.Text = ...,
        commodity_group: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["activity_time",b"activity_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["action_type",b"action_type","activity_name",b"activity_name","activity_time",b"activity_time","bl_qty",b"bl_qty","cargo_grade",b"cargo_grade","commodity_group",b"commodity_group","country",b"country","cp_unit",b"cp_unit","imo_no",b"imo_no","load_or_discharge",b"load_or_discharge","port",b"port","port_call_num",b"port_call_num","unctad_code",b"unctad_code","voyage_num",b"voyage_num","vsl_name",b"vsl_name"]) -> None: ...
global___VesonImosPortActivity = VesonImosPortActivity
