# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ptypes/masterdatapb/v1/veson_vip.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&ptypes/masterdatapb/v1/veson_vip.proto\x12$oceanbolt.com.ptypes.masterdatapb.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\x01\n\x1aVesonImosPortActivitySlice\x12\x64\n\x0fport_activities\x18\x01 \x03(\x0b\x32;.oceanbolt.com.ptypes.masterdatapb.v1.VesonImosPortActivityR\x0eportActivities\"\x88\x04\n\x15VesonImosPortActivity\x12\x1d\n\nvoyage_num\x18\x01 \x01(\x05R\tvoyageNum\x12\"\n\rport_call_num\x18\x02 \x01(\x05R\x0bportCallNum\x12?\n\ractivity_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0c\x61\x63tivityTime\x12#\n\ractivity_name\x18\x04 \x01(\tR\x0c\x61\x63tivityName\x12\x1f\n\x0b\x61\x63tion_type\x18\x05 \x01(\tR\nactionType\x12\x12\n\x04port\x18\x06 \x01(\tR\x04port\x12\x18\n\x07\x63ountry\x18\x07 \x01(\tR\x07\x63ountry\x12\x1f\n\x0bunctad_code\x18\x08 \x01(\tR\nunctadCode\x12\x19\n\x08vsl_name\x18\t \x01(\tR\x07vslName\x12\x15\n\x06imo_no\x18\n \x01(\x05R\x05imoNo\x12*\n\x11load_or_discharge\x18\x0b \x01(\tR\x0floadOrDischarge\x12\x1f\n\x0b\x63\x61rgo_grade\x18\x0c \x01(\tR\ncargoGrade\x12\x15\n\x06\x62l_qty\x18\r \x01(\x01R\x05\x62lQty\x12\x17\n\x07\x63p_unit\x18\x0e \x01(\tR\x06\x63pUnit\x12\'\n\x0f\x63ommodity_group\x18\x0f \x01(\tR\x0e\x63ommodityGroupBQZOgitlab.com/veson/oceanbolt/gen-proto-go/gen/ptypes/masterdatapb/v1;masterdatapbb\x06proto3')



_VESONIMOSPORTACTIVITYSLICE = DESCRIPTOR.message_types_by_name['VesonImosPortActivitySlice']
_VESONIMOSPORTACTIVITY = DESCRIPTOR.message_types_by_name['VesonImosPortActivity']
VesonImosPortActivitySlice = _reflection.GeneratedProtocolMessageType('VesonImosPortActivitySlice', (_message.Message,), {
  'DESCRIPTOR' : _VESONIMOSPORTACTIVITYSLICE,
  '__module__' : 'ptypes.masterdatapb.v1.veson_vip_pb2'
  # @@protoc_insertion_point(class_scope:oceanbolt.com.ptypes.masterdatapb.v1.VesonImosPortActivitySlice)
  })
_sym_db.RegisterMessage(VesonImosPortActivitySlice)

VesonImosPortActivity = _reflection.GeneratedProtocolMessageType('VesonImosPortActivity', (_message.Message,), {
  'DESCRIPTOR' : _VESONIMOSPORTACTIVITY,
  '__module__' : 'ptypes.masterdatapb.v1.veson_vip_pb2'
  # @@protoc_insertion_point(class_scope:oceanbolt.com.ptypes.masterdatapb.v1.VesonImosPortActivity)
  })
_sym_db.RegisterMessage(VesonImosPortActivity)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZOgitlab.com/veson/oceanbolt/gen-proto-go/gen/ptypes/masterdatapb/v1;masterdatapb'
  _VESONIMOSPORTACTIVITYSLICE._serialized_start=114
  _VESONIMOSPORTACTIVITYSLICE._serialized_end=244
  _VESONIMOSPORTACTIVITY._serialized_start=247
  _VESONIMOSPORTACTIVITY._serialized_end=767
# @@protoc_insertion_point(module_scope)
