# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ptypes/spatialpb/v1/port.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eptypes/spatialpb/v1/port.proto\x12!oceanbolt.com.ptypes.spatialpb.v1\"\x9b\x01\n\x04Port\x12\x17\n\x07port_id\x18\x01 \x01(\rR\x06portId\x12\x1b\n\tport_name\x18\x02 \x01(\tR\x08portName\x12\x16\n\x06region\x18\x03 \x01(\tR\x06region\x12!\n\x0c\x63ountry_code\x18\x04 \x01(\tR\x0b\x63ountryCode\x12\x10\n\x03lat\x18\x05 \x01(\x01R\x03lat\x12\x10\n\x03lon\x18\x06 \x01(\x01R\x03lonBKZIgitlab.com/veson/oceanbolt/gen-proto-go/gen/ptypes/spatialpb/v1;spatialpbb\x06proto3')



_PORT = DESCRIPTOR.message_types_by_name['Port']
Port = _reflection.GeneratedProtocolMessageType('Port', (_message.Message,), {
  'DESCRIPTOR' : _PORT,
  '__module__' : 'ptypes.spatialpb.v1.port_pb2'
  # @@protoc_insertion_point(class_scope:oceanbolt.com.ptypes.spatialpb.v1.Port)
  })
_sym_db.RegisterMessage(Port)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZIgitlab.com/veson/oceanbolt/gen-proto-go/gen/ptypes/spatialpb/v1;spatialpb'
  _PORT._serialized_start=70
  _PORT._serialized_end=225
# @@protoc_insertion_point(module_scope)
