"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.timestamp_pb2
import google.protobuf.wrappers_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class AisPositionExtended(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    LON_FIELD_NUMBER: builtins.int
    LAT_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    SPEED_FIELD_NUMBER: builtins.int
    NAVIGATIONAL_STATUS_FIELD_NUMBER: builtins.int
    DESTINATION_FIELD_NUMBER: builtins.int
    ETA_FIELD_NUMBER: builtins.int
    DRAUGHT_FIELD_NUMBER: builtins.int
    COURSE_FIELD_NUMBER: builtins.int
    HEADING_FIELD_NUMBER: builtins.int
    IMO_FIELD_NUMBER: builtins.int
    MMSI_FIELD_NUMBER: builtins.int
    lon: builtins.float
    lat: builtins.float
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def speed(self) -> google.protobuf.wrappers_pb2.DoubleValue: ...
    @property
    def navigational_status(self) -> google.protobuf.wrappers_pb2.Int32Value: ...
    destination: typing.Text
    @property
    def eta(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def draught(self) -> google.protobuf.wrappers_pb2.DoubleValue: ...
    @property
    def course(self) -> google.protobuf.wrappers_pb2.DoubleValue: ...
    @property
    def heading(self) -> google.protobuf.wrappers_pb2.DoubleValue: ...
    imo: builtins.int
    mmsi: builtins.int
    def __init__(self,
        *,
        lon: builtins.float = ...,
        lat: builtins.float = ...,
        timestamp: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        speed: typing.Optional[google.protobuf.wrappers_pb2.DoubleValue] = ...,
        navigational_status: typing.Optional[google.protobuf.wrappers_pb2.Int32Value] = ...,
        destination: typing.Text = ...,
        eta: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        draught: typing.Optional[google.protobuf.wrappers_pb2.DoubleValue] = ...,
        course: typing.Optional[google.protobuf.wrappers_pb2.DoubleValue] = ...,
        heading: typing.Optional[google.protobuf.wrappers_pb2.DoubleValue] = ...,
        imo: builtins.int = ...,
        mmsi: builtins.int = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["course",b"course","draught",b"draught","eta",b"eta","heading",b"heading","navigational_status",b"navigational_status","speed",b"speed","timestamp",b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["course",b"course","destination",b"destination","draught",b"draught","eta",b"eta","heading",b"heading","imo",b"imo","lat",b"lat","lon",b"lon","mmsi",b"mmsi","navigational_status",b"navigational_status","speed",b"speed","timestamp",b"timestamp"]) -> None: ...
global___AisPositionExtended = AisPositionExtended
