# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ptypes/enums/direction.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cptypes/enums/direction.proto\x12\x1aoceanbolt.com.ptypes.enums*`\n\tDirection\x12\x17\n\x13UNDEFINED_DIRECTION\x10\x00\x12\x05\n\x01N\x10\x01\x12\x06\n\x02NE\x10\x02\x12\x05\n\x01\x45\x10\x03\x12\x06\n\x02SE\x10\x04\x12\x05\n\x01S\x10\x05\x12\x06\n\x02SW\x10\x06\x12\x05\n\x01W\x10\x07\x12\x06\n\x02NW\x10\x08\x42:Z8gitlab.com/veson/oceanbolt/gen-proto-go/gen/ptypes/enumsb\x06proto3')

_DIRECTION = DESCRIPTOR.enum_types_by_name['Direction']
Direction = enum_type_wrapper.EnumTypeWrapper(_DIRECTION)
UNDEFINED_DIRECTION = 0
N = 1
NE = 2
E = 3
SE = 4
S = 5
SW = 6
W = 7
NW = 8


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z8gitlab.com/veson/oceanbolt/gen-proto-go/gen/ptypes/enums'
  _DIRECTION._serialized_start=60
  _DIRECTION._serialized_end=156
# @@protoc_insertion_point(module_scope)
