# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ptypes/enums/laden_status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fptypes/enums/laden_status.proto\x12\x1aoceanbolt.com.ptypes.enums*A\n\x0bLadenStatus\x12\x1a\n\x16UNDEFINED_LADEN_STATUS\x10\x00\x12\t\n\x05LADEN\x10\x01\x12\x0b\n\x07\x42\x41LLAST\x10\x02\x42:Z8gitlab.com/veson/oceanbolt/gen-proto-go/gen/ptypes/enumsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ptypes.enums.laden_status_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z8gitlab.com/veson/oceanbolt/gen-proto-go/gen/ptypes/enums'
  _LADENSTATUS._serialized_start=63
  _LADENSTATUS._serialized_end=128
# @@protoc_insertion_point(module_scope)
