# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ptypes/enums/navigational_status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&ptypes/enums/navigational_status.proto\x12\x1aoceanbolt.com.ptypes.enums*\xed\x02\n\x12NavigationalStatus\x12\x1f\n\x1bUNKNOWN_NAVIGATIONAL_STATUS\x10\x00\x12\x1a\n\x16UNDER_WAY_USING_ENGINE\x10\x64\x12\r\n\tAT_ANCHOR\x10\x01\x12\x15\n\x11NOT_UNDER_COMMAND\x10\x02\x12\x1e\n\x1aRESTRICTED_MANOEUVRABILITY\x10\x03\x12\x1a\n\x16\x43ONSTRAINED_BY_DRAUGHT\x10\x04\x12\n\n\x06MOORED\x10\x05\x12\x0b\n\x07\x41GROUND\x10\x06\x12\x16\n\x12\x45NGAGED_IN_FISHING\x10\x07\x12\x16\n\x12\x45NGAGED_IN_SAILING\x10\x08\x12%\n!POWER_DRIVEN_VESSEL_TOWING_ASTERN\x10\x0b\x12\x39\n5POWER_DRIVEN_VESSEL_PUSHING_AHEAD_OR_TOWING_ALONGSIDE\x10\x0c\x12\r\n\tUNDEFINED\x10\x0f\x42:Z8gitlab.com/veson/oceanbolt/gen-proto-go/gen/ptypes/enumsb\x06proto3')

_NAVIGATIONALSTATUS = DESCRIPTOR.enum_types_by_name['NavigationalStatus']
NavigationalStatus = enum_type_wrapper.EnumTypeWrapper(_NAVIGATIONALSTATUS)
UNKNOWN_NAVIGATIONAL_STATUS = 0
UNDER_WAY_USING_ENGINE = 100
AT_ANCHOR = 1
NOT_UNDER_COMMAND = 2
RESTRICTED_MANOEUVRABILITY = 3
CONSTRAINED_BY_DRAUGHT = 4
MOORED = 5
AGROUND = 6
ENGAGED_IN_FISHING = 7
ENGAGED_IN_SAILING = 8
POWER_DRIVEN_VESSEL_TOWING_ASTERN = 11
POWER_DRIVEN_VESSEL_PUSHING_AHEAD_OR_TOWING_ALONGSIDE = 12
UNDEFINED = 15


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z8gitlab.com/veson/oceanbolt/gen-proto-go/gen/ptypes/enums'
  _NAVIGATIONALSTATUS._serialized_start=71
  _NAVIGATIONALSTATUS._serialized_end=436
# @@protoc_insertion_point(module_scope)
