# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ptypes/enums/polygon_status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!ptypes/enums/polygon_status.proto\x12\x1aoceanbolt.com.ptypes.enums*w\n\rPolygonStatus\x12\x1c\n\x18UNDEFINED_POLYGON_STATUS\x10\x00\x12\x0b\n\x07IN_PORT\x10\x01\x12\x10\n\x0cIN_ANCHORAGE\x10\x02\x12\x0c\n\x08IN_BERTH\x10\x03\x12\x0f\n\x0bIN_SHIPYARD\x10\x04\x12\n\n\x06\x41T_SEA\x10\x05\x42:Z8gitlab.com/veson/oceanbolt/gen-proto-go/gen/ptypes/enumsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ptypes.enums.polygon_status_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z8gitlab.com/veson/oceanbolt/gen-proto-go/gen/ptypes/enums'
  _POLYGONSTATUS._serialized_start=65
  _POLYGONSTATUS._serialized_end=184
# @@protoc_insertion_point(module_scope)
