# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ptypes/filters/geofence_filter.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$ptypes/filters/geofence_filter.proto\x12\x1coceanbolt.com.ptypes.filters\"\xcd\x01\n\x08Geofence\x12\x1f\n\x0bgeofence_id\x18\x01 \x01(\tR\ngeofenceId\x12Q\n\rcenter_radius\x18\x07 \x01(\x0b\x32*.oceanbolt.com.ptypes.filters.CenterRadiusH\x00R\x0c\x63\x65nterRadius\x12\x41\n\x07polygon\x18\x08 \x01(\x0b\x32%.oceanbolt.com.ptypes.filters.PolygonH\x00R\x07polygonB\n\n\x08geometry\"Q\n\tGeofences\x12\x44\n\tgeofences\x18\x01 \x03(\x0b\x32&.oceanbolt.com.ptypes.filters.GeofenceR\tgeofences\"\x93\x02\n\x0eGeofenceFilter\x12\x12\n\x03wkt\x18\n \x01(\tH\x00R\x03wkt\x12\x1a\n\x07geojson\x18\x0b \x01(\tH\x00R\x07geojson\x12\x12\n\x03wkb\x18\x0c \x01(\x0cH\x00R\x03wkb\x12\x1f\n\nesri_shape\x18\r \x01(\x0cH\x00R\tesriShape\x12Q\n\rcenter_radius\x18\x0e \x01(\x0b\x32*.oceanbolt.com.ptypes.filters.CenterRadiusH\x00R\x0c\x63\x65nterRadius\x12\x41\n\x07polygon\x18\x0f \x01(\x0b\x32%.oceanbolt.com.ptypes.filters.PolygonH\x00R\x07polygonB\x06\n\x04\x64\x61ta\"J\n\x0c\x43\x65nterRadius\x12\x10\n\x03lon\x18\x01 \x01(\x01R\x03lon\x12\x10\n\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x16\n\x06radius\x18\x03 \x01(\x01R\x06radius\"F\n\x07Polygon\x12;\n\x06points\x18\x01 \x03(\x0b\x32#.oceanbolt.com.ptypes.filters.PointR\x06points\"+\n\x05Point\x12\x10\n\x03lon\x18\x01 \x01(\x01R\x03lon\x12\x10\n\x03lat\x18\x02 \x01(\x01R\x03latB<Z:gitlab.com/veson/oceanbolt/gen-proto-go/gen/ptypes/filtersb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ptypes.filters.geofence_filter_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z:gitlab.com/veson/oceanbolt/gen-proto-go/gen/ptypes/filters'
  _GEOFENCE._serialized_start=71
  _GEOFENCE._serialized_end=276
  _GEOFENCES._serialized_start=278
  _GEOFENCES._serialized_end=359
  _GEOFENCEFILTER._serialized_start=362
  _GEOFENCEFILTER._serialized_end=637
  _CENTERRADIUS._serialized_start=639
  _CENTERRADIUS._serialized_end=713
  _POLYGON._serialized_start=715
  _POLYGON._serialized_end=785
  _POINT._serialized_start=787
  _POINT._serialized_end=830
# @@protoc_insertion_point(module_scope)
