"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import oceanbolt.com.ptypes.enums.direction_pb2
import oceanbolt.com.ptypes.enums.navigational_status_pb2
import oceanbolt.com.ptypes.enums.polygon_status_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class PositionFilter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COURSE_FIELD_NUMBER: builtins.int
    HEADING_FIELD_NUMBER: builtins.int
    SPEED_FIELD_NUMBER: builtins.int
    DRAUGHT_METERS_FIELD_NUMBER: builtins.int
    DRAUGHT_PERCENTAGE_FIELD_NUMBER: builtins.int
    POLYGON_STATUS_FIELD_NUMBER: builtins.int
    DIRECTION_FIELD_NUMBER: builtins.int
    NAVIGATIONAL_STATUS_FIELD_NUMBER: builtins.int
    @property
    def course(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """Course range to filter on. Example: [0,45] (both values inclusive)."""
    @property
    def heading(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """Heading range to filter on. Example: [0,45] (both values inclusive)."""
    @property
    def speed(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """Speed range to filter on. Example: [0,12] (both values inclusive)."""
    @property
    def draught_meters(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """Draught range to filter on (value in meters). Example: [0,8] (both values inclusive)."""
    @property
    def draught_percentage(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """Draught percentage range to filter on (value in percentage). Example: [0.6,1] (both values inclusive)."""
    @property
    def polygon_status(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[ptypes.enums.polygon_status_pb2.PolygonStatus.ValueType]:
        """Polygon statuses to filter on. See oceanbolt.com.ptypes.enumspb.v1.PolygonStatus for list of valid values."""
    @property
    def direction(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[ptypes.enums.direction_pb2.Direction.ValueType]:
        """Directions to filter on. See oceanbolt.com.ptypes.enumspb.v1.Directions for list of valid values."""
    @property
    def navigational_status(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[ptypes.enums.navigational_status_pb2.NavigationalStatus.ValueType]:
        """Nav statuses to filter on. See oceanbolt.com.ptypes.enumspb.v1.NavigationalStatus for list of valid values."""
    def __init__(
        self,
        *,
        course: collections.abc.Iterable[builtins.float] | None = ...,
        heading: collections.abc.Iterable[builtins.float] | None = ...,
        speed: collections.abc.Iterable[builtins.float] | None = ...,
        draught_meters: collections.abc.Iterable[builtins.float] | None = ...,
        draught_percentage: collections.abc.Iterable[builtins.float] | None = ...,
        polygon_status: collections.abc.Iterable[ptypes.enums.polygon_status_pb2.PolygonStatus.ValueType] | None = ...,
        direction: collections.abc.Iterable[ptypes.enums.direction_pb2.Direction.ValueType] | None = ...,
        navigational_status: collections.abc.Iterable[ptypes.enums.navigational_status_pb2.NavigationalStatus.ValueType] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["course", b"course", "direction", b"direction", "draught_meters", b"draught_meters", "draught_percentage", b"draught_percentage", "heading", b"heading", "navigational_status", b"navigational_status", "polygon_status", b"polygon_status", "speed", b"speed"]) -> None: ...

global___PositionFilter = PositionFilter
