# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ptypes/vesselspb/v1/vessel.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ptypes/vesselspb/v1/vessel.proto\x12!oceanbolt.com.ptypes.vesselspb.v1\"\xa8\x01\n\x06Vessel\x12\x18\n\x07segment\x18\x01 \x01(\tR\x07segment\x12\x1f\n\x0bsub_segment\x18\x02 \x01(\tR\nsubSegment\x12\x14\n\x05\x62uilt\x18\x03 \x01(\rR\x05\x62uilt\x12\x1f\n\x0bvessel_name\x18\x04 \x01(\tR\nvesselName\x12\x1a\n\x08platform\x18\x05 \x01(\tR\x08platform\x12\x10\n\x03imo\x18\x06 \x01(\rR\x03imoBKZIgitlab.com/veson/oceanbolt/gen-proto-go/gen/ptypes/vesselspb/v1;vesselspbb\x06proto3')



_VESSEL = DESCRIPTOR.message_types_by_name['Vessel']
Vessel = _reflection.GeneratedProtocolMessageType('Vessel', (_message.Message,), {
  'DESCRIPTOR' : _VESSEL,
  '__module__' : 'ptypes.vesselspb.v1.vessel_pb2'
  # @@protoc_insertion_point(class_scope:oceanbolt.com.ptypes.vesselspb.v1.Vessel)
  })
_sym_db.RegisterMessage(Vessel)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZIgitlab.com/veson/oceanbolt/gen-proto-go/gen/ptypes/vesselspb/v1;vesselspb'
  _VESSEL._serialized_start=72
  _VESSEL._serialized_end=240
# @@protoc_insertion_point(module_scope)
