"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class VesselFilter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    IMO_FIELD_NUMBER: builtins.int
    HIGHLEVEL_TYPE_FIELD_NUMBER: builtins.int
    SEGMENT_FIELD_NUMBER: builtins.int
    SUB_SEGMENT_FIELD_NUMBER: builtins.int
    DWT_FIELD_NUMBER: builtins.int
    MAX_DRAUGHT_FIELD_NUMBER: builtins.int
    VESSEL_NAME_FIELD_NUMBER: builtins.int
    EX_NAME_FIELD_NUMBER: builtins.int
    LOA_FIELD_NUMBER: builtins.int
    BEAM_FIELD_NUMBER: builtins.int
    LOG_FITTED_FIELD_NUMBER: builtins.int
    SELF_UNLOADER_FIELD_NUMBER: builtins.int
    GEAR_FIELD_NUMBER: builtins.int
    ICE_CLASSED_FIELD_NUMBER: builtins.int
    MPV_FIELD_NUMBER: builtins.int
    GT_FIELD_NUMBER: builtins.int
    GRAIN_CAPACITY_FIELD_NUMBER: builtins.int
    GAS_CAPACITY_CBM_FIELD_NUMBER: builtins.int
    BUILT_FIELD_NUMBER: builtins.int
    PLATFORM_FIELD_NUMBER: builtins.int
    VESSEL_TYPE_FIELD_NUMBER: builtins.int
    FLAG_STATE_FIELD_NUMBER: builtins.int
    imo: builtins.int
    highlevel_type: typing.Text
    segment: typing.Text
    sub_segment: typing.Text
    @property
    def dwt(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def max_draught(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    vessel_name: typing.Text
    ex_name: typing.Text
    @property
    def loa(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def beam(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    log_fitted: builtins.bool
    self_unloader: builtins.bool
    gear: builtins.bool
    ice_classed: builtins.bool
    mpv: builtins.bool
    @property
    def gt(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def grain_capacity(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def gas_capacity_cbm(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def built(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    platform: typing.Text
    vessel_type: typing.Text
    flag_state: typing.Text
    def __init__(self,
        *,
        imo: builtins.int = ...,
        highlevel_type: typing.Text = ...,
        segment: typing.Text = ...,
        sub_segment: typing.Text = ...,
        dwt: typing.Optional[typing.Iterable[builtins.float]] = ...,
        max_draught: typing.Optional[typing.Iterable[builtins.float]] = ...,
        vessel_name: typing.Text = ...,
        ex_name: typing.Text = ...,
        loa: typing.Optional[typing.Iterable[builtins.float]] = ...,
        beam: typing.Optional[typing.Iterable[builtins.float]] = ...,
        log_fitted: builtins.bool = ...,
        self_unloader: builtins.bool = ...,
        gear: builtins.bool = ...,
        ice_classed: builtins.bool = ...,
        mpv: builtins.bool = ...,
        gt: typing.Optional[typing.Iterable[builtins.float]] = ...,
        grain_capacity: typing.Optional[typing.Iterable[builtins.float]] = ...,
        gas_capacity_cbm: typing.Optional[typing.Iterable[builtins.float]] = ...,
        built: typing.Optional[typing.Iterable[builtins.int]] = ...,
        platform: typing.Text = ...,
        vessel_type: typing.Text = ...,
        flag_state: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["beam",b"beam","built",b"built","dwt",b"dwt","ex_name",b"ex_name","flag_state",b"flag_state","gas_capacity_cbm",b"gas_capacity_cbm","gear",b"gear","grain_capacity",b"grain_capacity","gt",b"gt","highlevel_type",b"highlevel_type","ice_classed",b"ice_classed","imo",b"imo","loa",b"loa","log_fitted",b"log_fitted","max_draught",b"max_draught","mpv",b"mpv","platform",b"platform","segment",b"segment","self_unloader",b"self_unloader","sub_segment",b"sub_segment","vessel_name",b"vessel_name","vessel_type",b"vessel_type"]) -> None: ...
global___VesselFilter = VesselFilter
