# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ptypes/vesselspb/v1/vessel_filter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'ptypes/vesselspb/v1/vessel_filter.proto\x12!oceanbolt.com.ptypes.vesselspb.v1\x1a\x1egoogle/protobuf/wrappers.proto\"\xad\x05\n\x0cVesselFilter\x12\x10\n\x03imo\x18\x01 \x03(\rR\x03imo\x12%\n\x0ehighlevel_type\x18\x02 \x03(\tR\rhighlevelType\x12\x18\n\x07segment\x18\x03 \x03(\tR\x07segment\x12\x1f\n\x0bsub_segment\x18\x04 \x03(\tR\nsubSegment\x12\x10\n\x03\x64wt\x18\x05 \x03(\x01R\x03\x64wt\x12\x1f\n\x0bmax_draught\x18\x06 \x03(\x01R\nmaxDraught\x12\x10\n\x03loa\x18\t \x03(\x01R\x03loa\x12\x12\n\x04\x62\x65\x61m\x18\n \x03(\x01R\x04\x62\x65\x61m\x12\x39\n\nlog_fitted\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.BoolValueR\tlogFitted\x12?\n\rself_unloader\x18\x0c \x01(\x0b\x32\x1a.google.protobuf.BoolValueR\x0cselfUnloader\x12\x32\n\x06geared\x18\r \x01(\x0b\x32\x1a.google.protobuf.BoolValueR\x06geared\x12;\n\x0bice_classed\x18\x0e \x01(\x0b\x32\x1a.google.protobuf.BoolValueR\niceClassed\x12,\n\x03mpv\x18\x0f \x01(\x0b\x32\x1a.google.protobuf.BoolValueR\x03mpv\x12\x0e\n\x02gt\x18\x10 \x03(\x01R\x02gt\x12%\n\x0egrain_capacity\x18\x11 \x03(\x01R\rgrainCapacity\x12(\n\x10gas_capacity_cbm\x18\x12 \x03(\x01R\x0egasCapacityCbm\x12\x14\n\x05\x62uilt\x18\x13 \x03(\x05R\x05\x62uilt\x12\x1f\n\x0bvessel_type\x18\x15 \x03(\tR\nvesselType\x12\x1d\n\nflag_state\x18\x16 \x03(\tR\tflagStateBKZIgitlab.com/veson/oceanbolt/gen-proto-go/gen/ptypes/vesselspb/v1;vesselspbb\x06proto3')



_VESSELFILTER = DESCRIPTOR.message_types_by_name['VesselFilter']
VesselFilter = _reflection.GeneratedProtocolMessageType('VesselFilter', (_message.Message,), {
  'DESCRIPTOR' : _VESSELFILTER,
  '__module__' : 'ptypes.vesselspb.v1.vessel_filter_pb2'
  # @@protoc_insertion_point(class_scope:oceanbolt.com.ptypes.vesselspb.v1.VesselFilter)
  })
_sym_db.RegisterMessage(VesselFilter)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZIgitlab.com/veson/oceanbolt/gen-proto-go/gen/ptypes/vesselspb/v1;vesselspb'
  _VESSELFILTER._serialized_start=111
  _VESSELFILTER._serialized_end=796
# @@protoc_insertion_point(module_scope)
