# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ptypes/enumspb/v1/directions.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"ptypes/enumspb/v1/directions.proto\x12\x1foceanbolt.com.ptypes.enumspb.v1*a\n\nDirections\x12\x17\n\x13UNDEFINED_DIRECTION\x10\x00\x12\x05\n\x01N\x10\x01\x12\x06\n\x02NE\x10\x02\x12\x05\n\x01\x45\x10\x03\x12\x06\n\x02SE\x10\x04\x12\x05\n\x01S\x10\x05\x12\x06\n\x02SW\x10\x06\x12\x05\n\x01W\x10\x07\x12\x06\n\x02NW\x10\x08\x42GZEgitlab.com/veson/oceanbolt/gen-proto-go/gen/ptypes/enumspb/v1;enumspbb\x06proto3')

_DIRECTIONS = DESCRIPTOR.enum_types_by_name['Directions']
Directions = enum_type_wrapper.EnumTypeWrapper(_DIRECTIONS)
UNDEFINED_DIRECTION = 0
N = 1
NE = 2
E = 3
SE = 4
S = 5
SW = 6
W = 7
NW = 8


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZEgitlab.com/veson/oceanbolt/gen-proto-go/gen/ptypes/enumspb/v1;enumspb'
  _DIRECTIONS._serialized_start=71
  _DIRECTIONS._serialized_end=168
# @@protoc_insertion_point(module_scope)
