"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Directions:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _DirectionsEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Directions.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNDEFINED_DIRECTION: _Directions.ValueType  # 0
    N: _Directions.ValueType  # 1
    NE: _Directions.ValueType  # 2
    E: _Directions.ValueType  # 3
    SE: _Directions.ValueType  # 4
    S: _Directions.ValueType  # 5
    SW: _Directions.ValueType  # 6
    W: _Directions.ValueType  # 7
    NW: _Directions.ValueType  # 8
class Directions(_Directions, metaclass=_DirectionsEnumTypeWrapper):
    pass

UNDEFINED_DIRECTION: Directions.ValueType  # 0
N: Directions.ValueType  # 1
NE: Directions.ValueType  # 2
E: Directions.ValueType  # 3
SE: Directions.ValueType  # 4
S: Directions.ValueType  # 5
SW: Directions.ValueType  # 6
W: Directions.ValueType  # 7
NW: Directions.ValueType  # 8
global___Directions = Directions

