# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ptypes/enumspb/v1/laden_status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$ptypes/enumspb/v1/laden_status.proto\x12\x1foceanbolt.com.ptypes.enumspb.v1*A\n\x0bLadenStatus\x12\x1a\n\x16UNDEFINED_LADEN_STATUS\x10\x00\x12\t\n\x05LADEN\x10\x01\x12\x0b\n\x07\x42\x41LLAST\x10\x02\x42GZEgitlab.com/veson/oceanbolt/gen-proto-go/gen/ptypes/enumspb/v1;enumspbb\x06proto3')

_LADENSTATUS = DESCRIPTOR.enum_types_by_name['LadenStatus']
LadenStatus = enum_type_wrapper.EnumTypeWrapper(_LADENSTATUS)
UNDEFINED_LADEN_STATUS = 0
LADEN = 1
BALLAST = 2


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZEgitlab.com/veson/oceanbolt/gen-proto-go/gen/ptypes/enumspb/v1;enumspb'
  _LADENSTATUS._serialized_start=73
  _LADENSTATUS._serialized_end=138
# @@protoc_insertion_point(module_scope)
