# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ptypes/enumspb/v1/navigational_status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+ptypes/enumspb/v1/navigational_status.proto\x12\x1foceanbolt.com.ptypes.enumspb.v1*7\n\x12NavigationalStatus\x12!\n\x1dUNDEFINED_NAVIGATIONAL_STATUS\x10\x00\x42GZEgitlab.com/veson/oceanbolt/gen-proto-go/gen/ptypes/enumspb/v1;enumspbb\x06proto3')

_NAVIGATIONALSTATUS = DESCRIPTOR.enum_types_by_name['NavigationalStatus']
NavigationalStatus = enum_type_wrapper.EnumTypeWrapper(_NAVIGATIONALSTATUS)
UNDEFINED_NAVIGATIONAL_STATUS = 0


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZEgitlab.com/veson/oceanbolt/gen-proto-go/gen/ptypes/enumspb/v1;enumspb'
  _NAVIGATIONALSTATUS._serialized_start=80
  _NAVIGATIONALSTATUS._serialized_end=135
# @@protoc_insertion_point(module_scope)
