"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _NavigationalStatus:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _NavigationalStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_NavigationalStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNDEFINED_NAVIGATIONAL_STATUS: _NavigationalStatus.ValueType  # 0
class NavigationalStatus(_NavigationalStatus, metaclass=_NavigationalStatusEnumTypeWrapper):
    pass

UNDEFINED_NAVIGATIONAL_STATUS: NavigationalStatus.ValueType  # 0
global___NavigationalStatus = NavigationalStatus

