# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ptypes/entities/spatial.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dptypes/entities/spatial.proto\x12\x1doceanbolt.com.ptypes.entities\"\x9b\x01\n\x04Port\x12\x17\n\x07port_id\x18\x01 \x01(\rR\x06portId\x12\x1b\n\tport_name\x18\x02 \x01(\tR\x08portName\x12\x16\n\x06region\x18\x03 \x01(\tR\x06region\x12!\n\x0c\x63ountry_code\x18\x04 \x01(\tR\x0b\x63ountryCode\x12\x10\n\x03lat\x18\x05 \x01(\x01R\x03lat\x12\x10\n\x03lon\x18\x06 \x01(\x01R\x03lon\"\x08\n\x06RegionB=Z;gitlab.com/veson/oceanbolt/gen-proto-go/gen/ptypes/entitiesb\x06proto3')



_PORT = DESCRIPTOR.message_types_by_name['Port']
_REGION = DESCRIPTOR.message_types_by_name['Region']
Port = _reflection.GeneratedProtocolMessageType('Port', (_message.Message,), {
  'DESCRIPTOR' : _PORT,
  '__module__' : 'ptypes.entities.spatial_pb2'
  # @@protoc_insertion_point(class_scope:oceanbolt.com.ptypes.entities.Port)
  })
_sym_db.RegisterMessage(Port)

Region = _reflection.GeneratedProtocolMessageType('Region', (_message.Message,), {
  'DESCRIPTOR' : _REGION,
  '__module__' : 'ptypes.entities.spatial_pb2'
  # @@protoc_insertion_point(class_scope:oceanbolt.com.ptypes.entities.Region)
  })
_sym_db.RegisterMessage(Region)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z;gitlab.com/veson/oceanbolt/gen-proto-go/gen/ptypes/entities'
  _PORT._serialized_start=65
  _PORT._serialized_end=220
  _REGION._serialized_start=222
  _REGION._serialized_end=230
# @@protoc_insertion_point(module_scope)
