"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Vessel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SEGMENT_FIELD_NUMBER: builtins.int
    SUB_SEGMENT_FIELD_NUMBER: builtins.int
    BUILT_FIELD_NUMBER: builtins.int
    VESSEL_NAME_FIELD_NUMBER: builtins.int
    PLATFORM_FIELD_NUMBER: builtins.int
    IMO_FIELD_NUMBER: builtins.int
    segment: typing.Text
    sub_segment: typing.Text
    built: builtins.int
    vessel_name: typing.Text
    platform: typing.Text
    imo: builtins.int
    def __init__(self,
        *,
        segment: typing.Text = ...,
        sub_segment: typing.Text = ...,
        built: builtins.int = ...,
        vessel_name: typing.Text = ...,
        platform: typing.Text = ...,
        imo: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["built",b"built","imo",b"imo","platform",b"platform","segment",b"segment","sub_segment",b"sub_segment","vessel_name",b"vessel_name"]) -> None: ...
global___Vessel = Vessel
